Make dockerfile type discoverable

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,5 +1,5 @@
 #!/usr/bin/env sh
-set -e -o pipefail
+set -e -u -o pipefail
 
 k8s_cluster_cert=$K8S_CLUSTER_CERT
 k8s_cluster_name=$K8S_CLUSTER_NAME
@@ -25,6 +25,7 @@ echo "Getting ECR credentials"
 ecr_username=$(kubectl get secrets -n formbuilder-repos ecr-credentials -o jsonpath="{.data.ecr_username}" | base64 -d)
 ecr_password=$(kubectl get secrets -n formbuilder-repos ecr-credentials -o jsonpath="{.data.ecr_password}" | base64 -d)
 
+echo "Finding right ecr repos from ${k8s_namespace}"
 ecr_credentials=$(kubectl get secrets -n formbuilder-repos)
 
 for ecr_credential in ${ecr_credentials[@]}; do
@@ -39,12 +40,32 @@ for ecr_credential in ${ecr_credentials[@]}; do
     aws ecr get-login-password --region eu-west-2 | docker login --username ${ecr_username} --password-stdin ${ecr_password}
 
     echo  'Building docker image...'
-    docker build -t ${ECR_REPO_URL}:latest-${environment_name} -t ${ECR_REPO_URL}:${build_SHA} -f ./Dockerfile .
+    ecr_credential_match="${ecr_credentials_secret}-"
+    application_type=${ecr_credential#"$ecr_credential_match"}
 
-    echo 'Pushing latest docker image...'
-    docker push ${ECR_REPO_URL}:latest-${environment_name}
+    # if the ecr name doesn't have a type (e.g ecr-fb-user-datastore-api)
+    # then use Dockerfile.
+    # But if it has a type (e.g ecr-repo-fb-submitter-worker or
+    # ecr-repo-fb-submitter-api) the dockerfile to be build will be
+    # located in docker/worker/Dockerfile
+    #
+    if [[ $application_type == $ecr_credentials_secret ]]; then
+      dockerfile="./Dockerfile"
+    else
+      dockerfile="./docker/${application_type}/Dockerfile"
+    fi
 
-    echo 'Pushing current build SHA docker image...'
-    docker push ${ECR_REPO_URL}:${build_SHA}
+    if [[ -f $dockerfile ]]; then
+      docker build -t ${ECR_REPO_URL}:latest-${environment_name} -t ${ECR_REPO_URL}:${build_SHA} -f ${dockerfile} .
+
+      echo 'Pushing latest docker image...'
+      docker push ${ECR_REPO_URL}:latest-${environment_name}
+
+      echo 'Pushing current build SHA docker image...'
+      docker push ${ECR_REPO_URL}:${build_SHA}
+    else
+      echo "Dockerfile ${dockerfile} not found! :("
+      exit 1
+    fi
   fi
 done
