Add POD_NAME to deploy step
Unfortunately the fact `api`'s and `workers`'s exist mean we are unable
to use the `app_name`. Therefore we'll need to pass in the POD_NAME in
the deployment step for each environment.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -29,7 +29,9 @@ encoded_git_crypt_key=$ENCODED_GIT_CRYPT_KEY
 
 credential_name="${service_account}_${platform_environment}_${deployment_environment}"
 
-pod_name=${application_name}-${platform_environment}-${deployment_environment}
+################################################################
+## Begin setting kubernetes context
+################################################################
 
 echo -n ${k8s_cluster_cert} | base64 -d > ./ca.crt
 kubectl config set-cluster ${k8s_cluster_name} --certificate-authority=./ca.crt --server=https://api.${k8s_cluster_name}
@@ -86,7 +88,7 @@ helm_command="helm template deploy/${chartname} $helm_command --set circleSha1=$
 echo $helm_command
 
 ################################################################
-# End git-crypt
+# Begin applying configuration
 ################################################################
 
 echo "Writing ${environment_full_name} config to $config_file"
@@ -95,20 +97,37 @@ $helm_command > $config_file
 echo "Applying configuration"
 kubectl apply -f $config_file -n "${namespace}"
 
-echo "Rolling out and restarting pods"
-kubectl -n ${namespace} rollout restart deployment ${pod_name}
+################################################################
+# Begin rollout and restart
+################################################################
 
-kubectl -n ${namespace} rollout status deployment ${pod_name}
+current_images=$(kubectl get pods -n ${namespace} -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq)
 
-echo "Checking correct image was deployed"
-images=$(kubectl get pods -n ${namespace} -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq)
+for current_image in ${current_images}; do
+  if [[ $current_image == *$application_name* ]]; then
+    image_deployed=false
+    pod_name=$(echo ${current_image} | awk -F'formbuilder/' '{print $NF}' | cut -f1 -d":")
 
-for image in ${images}; do
-  if [[ $image == *$build_SHA* ]]; then
-    echo "Successfully rolled out and restarted ${pod_name} pods in ${namespace}"
-    exit 0
+    echo "Rolling out and restarting pods for ${pod_name}"
+    kubectl -n ${namespace} rollout restart deployment ${pod_name}
+
+    kubectl -n ${namespace} rollout status deployment ${pod_name}
+
+    echo "Checking correct image was deployed with sha: ${build_SHA}"
+    new_images=$(kubectl get pods -n ${namespace} -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq)
+
+    for image in ${new_images}; do
+      if [[ $image == *$build_SHA* ]]; then
+        echo "Successfully rolled out and restarted ${pod_name} pods in ${namespace}"
+        image_deployed=true
+      fi
+    done
+
+    if [[ "${image_deployed}" = false ]]; then
+      echo "Unable to find image using ${build_SHA}"
+      exit 1
+    fi
   fi
 done
 
-echo "Unable to find image using ${build_SHA}"
-exit 1
+echo "Rollout and restart completed"
